### ISSUE TITLE
XE5 Build

### ISSUE THREAD

**Issue by KimBracknell** [SigmaSciences/opaR#2]
Hi there - I am trying to build in XE5 after installing Spring4D and Tuples. I get errors at lines 219, 320, 408 and 470 of unit opaR.TSymbolicExpression as follows:
[dcc32 Error] opaR.SymbolicExpression.pas(219): E2250 There is no overloaded version of 'Create' that can be called with these arguments
vec := TIntegerVector.Create(Engine, [rowCount, columnCount]);

I would love to get this working. Is there an XE5 compatible version or small change I can make such as a new overloaded version of Create that will fix this problem?

Thanks,
Kim.

**Comment by rlsdevine** [comment]
Hi Kim - looks like it's related to the array initialisation option introduced in XE7 see here http://blog.marcocantu.com/blog/2014_september_dynamic_arrays_delphixe7.html
I'd try creating the integer array in a separate line and using it in the constructor. Let me know if that works and I'll change the code - probably early next week.

Cheers, Bob

**Comment by KimBracknell** [comment]
Thanks Bob - but perhaps a bit beyond my expertise.
Cheers,
Kim.

**Comment by rlsdevine** [comment]
Hi Kim - apologies I should have notified you that I've changed the code so it should work in XE5 now. 

Cheers, Bob

**Comment by KimBracknell** [comment]
Thanks Bob,

I have managed to get it running - bewdy!
Are there any Delphi sample projects available?

Cheers,
Kim.

**Comment by rlsdevine** [comment]
The integration tests have got lots of examples. E.g. the t-test in UnivariateStatsTests.pas shows how results are stored in a Generic vector. I've had to switch to other things for now but will be adding more examples in the coming weeks. If you have any problems you can get me at rdevine at sigmasciences (with usual dot com).

**Comment by KimBracknell** [comment]
Thx Bob - all good!
