### ISSUE TITLE
TOSVersion.Architecture

### ISSUE THREAD

**Issue by davidberneda** [SigmaSciences/opaR#3]
There are a couple of uses of TOSVersion.Architecture that I think should be replaced with {$IFDEF CPUX64}.  If I'm running a 32bit executable in Windows 64bit, I can only use R 32bit, not force always to load R 64bit.

opaR.NativeUtility:

```
//if TOSVersion.Architecture = arIntelx86 then
{$IFNDEF CPUX64}
  subKey := 'R';
{$ELSE}
  subKey := 'R64';
{$ENDIF}

    {$IFDEF CPUX64}
    //if TOSVersion.Architecture = arIntelx64 then
      result := TPath.Combine(path, 'x64');
    //else
    {$ELSE}
      result := TPath.Combine(path, 'i386');
    {$ENDIF}
```

**Comment by rlsdevine** [comment]
Ah good point I'll change that over the weekend
